# Generated by Django 3.0.4 on 2020-03-19 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='shared.Country'),
        ),
        migrations.AddField(
            model_name='entity',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entity.Entity'),
        ),
        migrations.AddField(
            model_name='agent',
            name='entity',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Entity'),
        ),
        migrations.AddField(
            model_name='agent',
            name='informations',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
