# Generated by Django 3.0.4 on 2020-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20200521_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='587694', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='691513275', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='304409', max_length=10, unique=True),
        ),
    ]
