# Generated by Django 3.0.4 on 2020-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20200319_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='136105', max_length=10, unique=True),
        ),
    ]
