# Generated by Django 3.0.4 on 2020-03-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20200319_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='518175', max_length=10, unique=True),
        ),
    ]
