# Generated by Django 3.0.4 on 2020-03-21 13:28

from django.db import migrations, models
import entity.models.entity


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20200319_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='catetory',
        ),
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.CharField(choices=[(entity.models.entity.EntityType['PROVIDER'], 'PROVIDER'),
                                            (entity.models.entity.EntityType['DISTRIBUTEUR'],
                                             'DISTRIBUTEUR'), (entity.models.entity.EntityType['BANQUE'], 'BANQUE')],
                                   default='PROVIDER', max_length=30),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='078154', max_length=10, unique=True),
        ),
    ]
