# Generated by Django 3.0.4 on 2020-07-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20200522_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='878715', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='978254143', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='145061', max_length=10, unique=True),
        ),
    ]
