# Generated by Django 3.0.4 on 2020-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_auto_20200321_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='072280', max_length=10, unique=True),
        ),
    ]
