# Generated by Django 3.0.4 on 2020-10-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_auto_20200723_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='habilitation',
            field=models.CharField(choices=[('AGENT', 'AGENT'), ('SUPERVISEUR', 'SUPERVISEUR'), ('ADMIINISTRATEUR', 'ADMIINISTRATEUR'), ('AGENT_FINANCE', 'AGENT_FINANCE')], default='AGENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='446731', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='404783507', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='736709', max_length=10, unique=True),
        ),
    ]
