# Generated by Django 3.0.4 on 2020-04-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_auto_20200405_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='code',
            field=models.CharField(default='086796', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='144637818', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='047948', max_length=10, unique=True),
        ),
    ]
