# Generated by Django 3.0.4 on 2020-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_auto_20200405_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='131672', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='613306132', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.CharField(choices=[('PROVIDER', 'PROVIDER'), ('DISTRIBUTEUR', 'DISTRIBUTEUR'), ('BANQUE', 'BANQUE'), ('BUSINESS_PARTNER', 'BUSINESS_PARTNER')], default='PROVIDER', max_length=30),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='795618', max_length=10, unique=True),
        ),
    ]
