# Generated by Django 3.0.4 on 2020-04-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0017_currency'),
        ('entity', '0012_auto_20200429_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitysettings',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.Currency'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='788305', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='959904982', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='878002', max_length=10, unique=True),
        ),
    ]
