# Generated by Django 3.0.4 on 2020-05-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_auto_20200429_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitysettings',
            options={'verbose_name': 'Entity setting', 'verbose_name_plural': 'Entity settings'},
        ),
        migrations.RemoveField(
            model_name='entitysettings',
            name='currency',
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='612108', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='216272960', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='195396', max_length=10, unique=True),
        ),
    ]
