# Generated by Django 3.0.4 on 2020-05-08 12:31

import core.utils.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0014_auto_20200505_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='secret_key',
            field=models.CharField(default=core.utils.string.generate_secret_key, max_length=16),
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='068269', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='496691665', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='920239', max_length=10, unique=True),
        ),
    ]
