# Generated by Django 3.0.4 on 2020-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_auto_20200508_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='secret_key',
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='618991', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='943729427', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='999139', max_length=10, unique=True),
        ),
    ]
