# Generated by Django 3.0.4 on 2020-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_auto_20200508_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='authentication_type',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('OTP', 'OTP')], default='DEFAULT', max_length=30),
        ),
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default='329097', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='account_number',
            field=models.CharField(default='524474912', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(default='418360', max_length=10, unique=True),
        ),
    ]
