# Generated by Django 3.0.4 on 2020-03-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
