# Generated by Django 3.0.4 on 2020-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_auto_20200522_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grille',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='grille',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
