# Generated by Django 3.0.4 on 2020-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_auto_20200522_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridor',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_TO_CASH', 'CASH_TO_CASH'), ('CASH_TO_WALLET', 'CASH_TO_WALLET'), ('WALLET_TO_CASH', 'WALLET_TO_CASH'), ('WALLET_TO_WALLET', 'WALLET_TO_WALLET'), ('RETRAIT_CASH', 'RETRAIT_CASH'), ('ACTIVATION_CARTE', 'ACTIVATION_CARTE'), ('CREATION_WALLET', 'CREATION_WALLET'), ('CREDIT_COMPTE_ENTITE', 'CREDIT_COMPTE_ENTITE'), ('DEBIT_COMPTE_ENTITE', 'DEBIT_COMPTE_ENTITE'), ('CASH_TO_BANK_ACCOUNT', 'CASH_TO_BANK_ACCOUNT'), ('WALLET_TO_BANK_ACCOUNT', 'WALLET_TO_BANK_ACCOUNT')], max_length=30),
        ),
    ]
