# Generated by Django 3.0.4 on 2020-03-19 21:39

from django.db import migrations, models
import shared.models.price


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_corridor_grille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grille',
            name='fee_type',
            field=models.CharField(choices=[(shared.models.price.FeeType['CONST'], 'CONSTANTE'), (shared.models.price.FeeType['PERCENT'], 'PERCENTAGE')], max_length=5),
        ),
    ]
