# Generated by Django 3.0.4 on 2020-03-21 13:23

from django.db import migrations, models
import shared.models.account
import shared.models.price


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_auto_20200319_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='catetory',
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[(shared.models.account.AccountType['PRINCIPAL'], 1), (
                shared.models.account.AccountType['COMMISSION'], 2)], default=shared.models.account.AccountType['PRINCIPAL'], max_length=15),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='transaction_type',
            field=models.CharField(choices=[(shared.models.price.TransactionType['CASH_TO_CASH'], 'CASH_TO_CASH'), (
                shared.models.price.TransactionType['RETRAIT_CASH'], 'RETRAIT_CASH')], max_length=5),
        ),
    ]
