# Generated by Django 3.0.4 on 2020-04-05 16:45

from django.db import migrations, models
import django.db.models.deletion
import shared.models.account


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shared', '0005_auto_20200321_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[(
                1, 1), (2, 2)], default=shared.models.account.AccountType['PRINCIPAL'], max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'entity'), ('model', 'entity')), models.Q(
                ('app_label', 'kyc'), ('model', 'customer')), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='account',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='destination_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'entity'), ('model', 'entity')), models.Q(('app_label', 'shared'), ('model', 'country')),
                                                                          _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corridor_destination_content_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='destination_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='source_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'entity'), ('model', 'entity')), models.Q(('app_label', 'shared'), ('model', 'country')),
                                                                          _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corridor_source_content_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='transaction_type',
            field=models.CharField(
                choices=[('ENVOI_CASH', 'ENVOI_CASH'), ('RETRAIT_CASH', 'RETRAIT_CASH')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grille',
            name='fee_type',
            field=models.CharField(
                choices=[('CONSTANTE', 'CONSTANTE'), ('PERCENTAGE', 'PERCENTAGE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='grille',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
