# Generated by Django 3.0.4 on 2020-04-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_auto_20200405_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[(1, 1), (2, 2)], default=1, max_length=30),
        ),
    ]
