# Generated by Django 3.0.4 on 2020-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_auto_20200411_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corridor',
            name='destination_content_type',
        ),
        migrations.RemoveField(
            model_name='corridor',
            name='destination_object_id',
        ),
        migrations.RemoveField(
            model_name='corridor',
            name='source_content_type',
        ),
        migrations.RemoveField(
            model_name='corridor',
            name='source_object_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[(
                'PRINCIPAL', 'PRINCIPAL'), ('COMMISSION', 'COMMISSION')], default='PRINCIPAL', max_length=30),
        ),
    ]
