# Generated by Django 3.0.4 on 2020-04-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_auto_20200411_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridor',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_country', to='shared.Country'),
        ),
        migrations.AddField(
            model_name='corridor',
            name='source_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_country', to='shared.Country'),
        ),
    ]
