# Generated by Django 3.0.4 on 2020-04-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_auto_20200411_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridor',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_TO_CASH', 'CASH_TO_CASH'), ('RETRAIT_CASH', 'RETRAIT_CASH')], max_length=20),
        ),
    ]
