# Generated by Django 3.0.4 on 2020-04-12 20:24

from django.db import migrations, models
import shared.models.price


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_auto_20200412_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('calculation_expression', models.TextField(validators=[shared.models.price.validate_calculation_expression])),
            ],
            options={
                'verbose_name': 'Revenue Sharing',
            },
        ),
    ]
