# Generated by Django 3.0.4 on 2020-04-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_sharing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing',
            name='revenue',
        ),
    ]
