# Generated by Django 3.0.4 on 2020-04-13 13:55

from django.db import migrations, models
import django.db.models.deletion
import shared.models.price


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_remove_sharing_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sharing',
            name='name',
        ),
        migrations.AddField(
            model_name='sharing',
            name='corridor',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.Corridor'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='calculation_expression',
            field=models.TextField(help_text='FRAIS/2->PROVIDER:0.2:CREDIT;BANQUE:0.4:CREDIT',
                                   validators=[shared.models.price.validate_calculation_expression]),
        ),
    ]
