# Generated by Django 3.0.4 on 2020-04-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0017_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='grille',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.Currency'),
        ),
    ]
