# Generated by Django 3.0.4 on 2020-04-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0020_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'verbose_name': 'Change', 'verbose_name_plural': 'Changes'},
        ),
        migrations.AddField(
            model_name='change',
            name='parity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.Currency'),
        ),
    ]
