# Generated by Django 3.0.4 on 2020-05-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0021_auto_20200429_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridor',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_TO_CASH', 'CASH_TO_CASH'), ('RETRAIT_CASH', 'RETRAIT_CASH'), ('ACTIVATION_CARTE', 'ACTIVATION_CARTE')], max_length=20),
        ),
    ]
