# Generated by Django 3.0.4 on 2020-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0022_auto_20200501_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('PRINCIPAL', 'PRINCIPAL'), ('COMMISSION', 'COMMISSION'), ('CARTE_MONNAMON', 'CARTE_MONNAMON')], default='PRINCIPAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_TO_CASH', 'CASH_TO_CASH'), ('RETRAIT_CASH', 'RETRAIT_CASH'), ('ACTIVATION_CARTE', 'ACTIVATION_CARTE'), ('CREATION_WALLET', 'CREATION_WALLET'), ('RECHARGEMENT_COMPTE_ENTITE', 'RECHARGEMENT_COMPTE_ENTITE')], max_length=30),
        ),
    ]
