# Generated by Django 3.0.4 on 2020-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0023_auto_20200503_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='parity',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='corridor',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_TO_CASH', 'CASH_TO_CASH'), ('CASH_TO_WALLET', 'CASH_TO_WALLET'), ('WALLET_TO_CASH', 'WALLET_TO_CASH'), ('WALLET_TO_WALLET', 'WALLET_TO_WALLET'), ('RETRAIT_CASH', 'RETRAIT_CASH'), ('ACTIVATION_CARTE', 'ACTIVATION_CARTE'), ('CREATION_WALLET', 'CREATION_WALLET'), ('CREDIT_COMPTE_ENTITE', 'CREDIT_COMPTE_ENTITE'), ('DEBIT_COMPTE_ENTITE', 'DEBIT_COMPTE_ENTITE')], max_length=30),
        ),
    ]
