# Generated by Django 3.0.4 on 2020-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0024_auto_20200509_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='change',
            name='parity',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
        ),
    ]
