# Generated by Django 3.0.4 on 2020-05-17 16:29

from django.db import migrations, models
import shared.models.price


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0026_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grille',
            options={'verbose_name': 'Pricing'},
        ),
        migrations.AddField(
            model_name='sharing',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Tell if this is the standard sharing to use for this corridor'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='calculation_expression',
            field=models.CharField(help_text='FRAIS/2=>PROVIDER:0.2:+;BANQUE:0.4:-', max_length=200, validators=[shared.models.price.validate_calculation_expression]),
        ),
    ]
