# Generated by Django 3.0.4 on 2020-05-21 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20200521_2359'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='17021603', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='1145126609', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction_number',
            field=models.CharField(blank=True, default='7684656174', max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='RevenuSharingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Entity')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.Transaction')),
            ],
            options={
                'verbose_name': 'Revenu Sharing result',
                'verbose_name_plural': 'Revenu Sharing result',
            },
        ),
    ]
