# Generated by Django 3.0.4 on 2020-06-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_motifenvoi_sourcerevenu'),
        ('transaction', '0003_auto_20200618_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='motif_envoi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_motif_envoi', to='shared.MotifEnvoi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_revenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_source_revenu', to='shared.SourceRevenu'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='32778090', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='3188369856', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction_number',
            field=models.CharField(blank=True, default='1465632578', max_length=11, null=True),
        ),
    ]
