# Generated by Django 3.0.4 on 2020-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200412_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='19570774', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='1766389699', max_length=11, unique=True),
        ),
    ]
