# Generated by Django 3.0.4 on 2020-04-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_auto_20200413_1608'),
        ('transaction', '0005_auto_20200412_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='35238510', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='8092848577', max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('balance_after_operation', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='shared.Account')),
                ('transaction', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.Transaction')),
            ],
            options={
                'verbose_name': 'Operation detail',
                'verbose_name_plural': 'Operatons details',
            },
        ),
    ]
