# Generated by Django 3.0.4 on 2020-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20200629_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='891522621', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='3330255616', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction_number',
            field=models.CharField(blank=True, default='7073259096', max_length=11, null=True),
        ),
    ]
