# Generated by Django 3.0.4 on 2020-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20200413_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('SUSPENDED', 'SUSPENDED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='86362435', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='9926913341', max_length=11, unique=True),
        ),
    ]
