# Generated by Django 3.0.4 on 2020-08-05 18:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20200706_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payload',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='906484095', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='4672644609', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction_number',
            field=models.CharField(blank=True, default='3130249004', max_length=11, null=True),
        ),
    ]
