# Generated by Django 3.0.4 on 2020-11-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20200805_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenusharingresult',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='617592744', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='6863834637', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction_number',
            field=models.CharField(blank=True, default='9853739420', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_TO_CASH', 'CASH_TO_CASH'), ('CASH_TO_WALLET', 'CASH_TO_WALLET'), ('WALLET_TO_CASH', 'WALLET_TO_CASH'), ('WALLET_TO_WALLET', 'WALLET_TO_WALLET'), ('RETRAIT_CASH', 'RETRAIT_CASH'), ('ACTIVATION_CARTE', 'ACTIVATION_CARTE'), ('CREATION_WALLET', 'CREATION_WALLET'), ('CREDIT_COMPTE_ENTITE', 'CREDIT_COMPTE_ENTITE'), ('DEBIT_COMPTE_ENTITE', 'DEBIT_COMPTE_ENTITE'), ('CASH_TO_BANK_ACCOUNT', 'CASH_TO_BANK_ACCOUNT'), ('WALLET_TO_BANK_ACCOUNT', 'WALLET_TO_BANK_ACCOUNT'), ('BATCH', 'BATCH')], default='CASH_TO_CASH', max_length=30),
        ),
    ]
