# Generated by Django 3.0.4 on 2020-04-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20200417_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='97542983', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='5362117587', max_length=11, unique=True),
        ),
    ]
