# Generated by Django 3.0.4 on 2020-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_auto_20200418_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='parent',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='43954563', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='5159306208', max_length=11, unique=True),
        ),
    ]
