# Generated by Django 3.0.4 on 2020-04-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transaction', '0013_auto_20200418_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='92931805', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'entity'), ('model', 'entity')), models.Q(('app_label', 'kyc'), ('model', 'customer')),
                                                                          _connector='OR'), null=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_content_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='4635250609', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'entity'), ('model', 'entity')), models.Q(('app_label', 'kyc'), (
                'model', 'customer')), _connector='OR'), null=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_content_type', to='contenttypes.ContentType'),
        ),
    ]
