# Generated by Django 3.0.4 on 2020-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_auto_20200429_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='64584438', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='5146238666', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction_number',
            field=models.CharField(blank=True, default='4087324013', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_TO_CASH', 'CASH_TO_CASH'), ('RETRAIT_CASH', 'RETRAIT_CASH'), ('ACTIVATION_CARTE', 'ACTIVATION_CARTE'), ('CREATION_WALLET', 'CREATION_WALLET'), ('RECHARGEMENT_COMPTE_ENTITE', 'RECHARGEMENT_COMPTE_ENTITE')], default='CASH_TO_CASH', max_length=30),
        ),
    ]
