# Generated by Django 3.0.4 on 2020-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0020_auto_20200503_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='92580683', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='5786400099', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction_number',
            field=models.CharField(blank=True, default='2637660487', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_TO_CASH', 'CASH_TO_CASH'), ('CASH_TO_WALLET', 'CASH_TO_WALLET'), ('WALLET_TO_CASH', 'WALLET_TO_CASH'), ('WALLET_TO_WALLET', 'WALLET_TO_WALLET'), ('RETRAIT_CASH', 'RETRAIT_CASH'), ('ACTIVATION_CARTE', 'ACTIVATION_CARTE'), ('CREATION_WALLET', 'CREATION_WALLET'), ('CREDIT_COMPTE_ENTITE', 'CREDIT_COMPTE_ENTITE'), ('DEBIT_COMPTE_ENTITE', 'DEBIT_COMPTE_ENTITE')], default='CASH_TO_CASH', max_length=30),
        ),
    ]
