# Generated by Django 3.0.4 on 2020-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_auto_20200509_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='72288102', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='3612762603', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_transaction_number',
            field=models.CharField(blank=True, default='4761078166', max_length=11, null=True),
        ),
    ]
