# Generated by Django 3.0.4 on 2020-05-21 11:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(blank=True, max_length=10, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=10, null=True)),
                ('identification_document_deleivery_date', models.DateField(default=datetime.date.today, verbose_name='Document deleivery date')),
                ('identification_document_expiry_date', models.DateField(default=datetime.date.today, verbose_name='Document expiry date')),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='residence_country', to='shared.Country')),
                ('informations', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issuer_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared.Country')),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('card_identification_number', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kyc.Customer')),
            ],
            options={
                'verbose_name': 'Cartera',
            },
        ),
    ]
