# Generated by Django 3.0.4 on 2020-04-30 00:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20200405_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identification_document_deleivery_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Deleivery date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='identification_document_expiry_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Deleivery date'),
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('ccard_identification_number', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kyc.Customer')),
            ],
            options={
                'verbose_name': 'Cartera',
            },
        ),
    ]
