# Generated by Django 3.0.4 on 2020-06-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20200615_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='relations',
            field=models.ManyToManyField(related_name='_customer_relations_+', to='kyc.Customer'),
        ),
    ]
