# Generated by Django 3.0.4 on 2020-05-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20200527_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='identification_document_deleivery_date',
            new_name='identification_document_delivery_date',
        ),
    ]
