# Generated by Django 3.0.4 on 2020-04-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20200430_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartera',
            old_name='ccard_identification_number',
            new_name='card_identification_number',
        ),
    ]
