# Generated by Django 3.0.4 on 2020-05-01 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0022_auto_20200501_1630'),
        ('kyc', '0004_auto_20200430_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='residence_country', to='shared.Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification_document_deleivery_date',
            field=models.DateField(default=datetime.date.today, verbose_name=' Document deleivery date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification_document_expiry_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Document expiry date'),
        ),
    ]
