# Generated by Django 3.0.4 on 2020-06-15 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_customer_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identification_document_delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Document delivery date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification_document_expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Document expiry date'),
        ),
    ]
